src/Entity/Category.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CategoryRepository")
 */
class Category
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $parent_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\QuestionAnswer", mappedBy="category")
     */
    private $questionAnswers;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $main_category;

    public function __construct()
    {
        $this->questionAnswers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getParentId(): ?int
    {
        return $this->parent_id;
    }

    public function setParentId(?int $parent_id): self
    {
        $this->parent_id = $parent_id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|QuestionAnswer[]
     */
    public function getQuestionAnswers(): Collection
    {
        return $this->questionAnswers;
    }

    public function addQuestionAnswer(QuestionAnswer $questionAnswer): self
    {
        if (!$this->questionAnswers->contains($questionAnswer)) {
            $this->questionAnswers[] = $questionAnswer;
            $questionAnswer->setCategory($this);
        }

        return $this;
    }

    public function removeQuestionAnswer(QuestionAnswer $questionAnswer): self
    {
        if ($this->questionAnswers->contains($questionAnswer)) {
            $this->questionAnswers->removeElement($questionAnswer);
            // set the owning side to null (unless already changed)
            if ($questionAnswer->getCategory() === $this) {
                $questionAnswer->setCategory(null);
            }
        }

        return $this;
    }

    public function getMainCategory(): ?string
    {
        return $this->main_category;
    }

    public function setMainCategory(string $main_category): self
    {
        $this->main_category = $main_category;

        return $this;
    }

}

templates/404_not_found.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {{ parent() }}
    <h1>{{ message }}</h1>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
            <style>
                a {
                    display: block;
                }
                body {
                    width: 95%;
                    margin: auto !important;
                }
                button.btn-primary {
                    display: block;
                    margin-bottom: 2%;
                }
                .like-dislike {
                    text-align: center;
                }
                .like-dislike i {
                    margin: 0 15px;
                    color: blue;
                }
                button[type="submit"] {
                    margin-bottom: 0;
                }

                #category_parent {
                    display: flex;
                    justify-content: space-between;
                }

                #categories {
                    width: 35%;
                }

                #answers {
                    width: 98%;
                }

                .msg {
                    text-align: center;
                }
            </style>
        {% endblock %}
    </head>
    <body>
        {% block body %}
            <a style="display: block; text-align: center" href="{{ path('faq') }}">NACHALO</a><br>
        {% endblock %}
        {% block javascripts %}
            <!-- jQuery library -->
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

            <!-- Popper JS -->
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>

            <!-- Latest compiled JavaScript -->
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
        {% endblock %}
    </body>
</html>

templates/faq.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {{ parent() }}
    <h1>MAIN</h1>
    <section>
        {% for entity in entities %}
           {# {% if not entity.questionAnswers.isEmpty %}
                <button type="button" class="btn btn-primary" data-toggle="collapse"
                        data-target="#questions">{{ entity.name }}</button>

                <div id="questions" class="collapse">
                    {% for qa in entity.questionAnswers %}
                        <h3>{{ qa.question }}</h3>
                        <p>{{ qa.answer }}</p>
                    {% endfor %}
                </div>
            {% else %} #}
                <a href="{{ path('subcategories1', {main: entity.mainCategory, c: entity.id }) }}">
                    {{ entity.name }}
                </a>


        {% endfor %}
    </section>
{% endblock %}

templates/faqMainCategories.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {{ parent() }}
    <form action="{{ path('search', {'main': main}) }}" method="post">
        <div class="form-group">
            <input type="text" class="form-control" name="search_box" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-primary mb-2" style="margin-left: auto">SEARCH</button>
    </form>
    <section id="category_parent">

        <section id="categories">
            {% for entity in entities %}
                {% set categoryName = entity.name|replace({' ':'-'})|lower %}

                    {% if not entity.questionAnswers is empty %}
                        <button type="button" class="btn btn-primary" data-toggle="collapse"
                                data-target="#q_{{ categoryName }}">{{ entity.name }}</button>
                    {% else %}
                        <a href="{{ path('subcategories1', {main: entity.mainCategory, c: entity.id}) }}">
                            {{ entity.name }}
                        </a>
                    {% endif %}

            {% endfor %}
        </section>
        <section id="answers">
            {% for entity in entities %}
                {% set categoryName = entity.name|replace({' ':'-'})|lower %}

                <div id="q_{{ categoryName }}" class="collapse card" data-parent="#category_parent">
                    {{ dump(app.request.cookies.get('voted')) }}
                    {% for qa in entity.questionAnswers %}
                        {% set votedQuestions = app.request.cookies.get('voted') %}

                        <div class="card-body" data-question="{{ qa.id }}">
                            <h5>{{ loop.index }}. {{ qa.question }}</h5><hr>
                            <p>{{ qa.answer|raw }}</p>

                            <button type="button" class="btn btn-info">Statistic</button>

                            {% if qa.id in votedQuestions %}
                                <p class="msg">Thanks</p>
                            {% else %}
                                <div class="like-dislike js-like-dislike">
                                    <i class="fa fa-thumbs-up" data-reaction="{{ reactions['like'][0].id }}"></i>
                                    <i class="fa fa-thumbs-down" data-toggle="modal" data-target="#myModal_{{ qa.id }}"></i>

                                    <div class="modal fade" id="myModal_{{ qa.id }}" tabindex="-1" role="dialog">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">What's wrong with this answer ?</h5>
                                                </div>
                                                <div class="modal-body">
                                                    <form class="js-dislike-form">
                                                        {% for dislike in reactions['dislike'] %}
                                                            <div class="form-check">
                                                                <input class="form-check-input" type="checkbox" name="dislike{{ loop.index }}" value="{{ dislike.id }}" id="exampleCheck{{ loop.index }}">
                                                                <label class="form-check-label" for="exampleCheck{{ loop.index }}">{{ dislike.reason }}</label>
                                                            </div>
                                                        {% endfor %}
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                            <button type="submit" class="btn btn-primary">Send message</button>
                                                        </div>
                                                    </form>
                                                    <div class="alert alert-danger" role="alert" hidden></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <p class="msg"></p>
                                </div>
                            {% endif %}

                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
        </section>
    </section>
{% endblock body %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/questionReaction.js') }}"></script>
    <script>
        $(document).ready(function () {
            $parent = $('#category_parent');

            var reaction = new Reaction($parent);

        });
    </script>
{% endblock javascripts %}

templates/formtest.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h1>NEW</h1>

    {{ form_start(formtest) }}
        {{ form_widget(formtest) }}
        <button type="submit">new</button>
    {{ form_end(formtest) }}
{% endblock %}

templates/questions.html.twig
{% extends 'base.html.twig' %}
{% block body %}


{% endblock %}

templates/statistic.html.twig
{% extends 'base.html.twig' %}
<<<<<<< HEAD
{% block body %}
    {% for question in questions %}
        <h1>{{ question.question }}</h1>
        <p>{{ question.answer|raw }}</p>
    {% endfor %}
=======
>>>>>>> 5630818ee1385d75db060ac740b5f480fcec89a2

{% block body %}
    {% for question in questions %}
        <h1>{{ question.question }}</h1>
        <p>{{ question.answer|raw }}</p>
    {% endfor %}
{% endblock %}